import Head from "next/head";
import "../styles/globals.css";
function MyApp({ Component, pageProps }) {
  return (
    <div>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <meta charSet="utf-8" />
          <link
            rel="icon"
            href="https://drive.google.com/file/d/1fVD8ZsSK_CYaAjQiASItvznMMaoxeVho/view?usp=sharing"
          />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="theme-color" content="#000000" />
          <meta
            name="description"
            content="Web site created using create-react-app"
          />
          <link
            rel="apple-touch-icon"
            href="https://drive.google.com/file/d/1fVD8ZsSK_CYaAjQiASItvznMMaoxeVho/view?usp=sharing"
          />

          <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
          <title>RENT 🤍NFT </title>
          <meta name="title" content="RENT LUV NFT MARKETPLACE" />
          <meta
            name="description"
            content="Rent services, products and homes with NFT technology"
          />

          <meta property="og:type" content="website" />
          <meta property="og:url" content="https://rent.luvnft.com/" />
          <meta property="og:title" content="RENT LUV NFT MARKETPLACE" />
          <meta
            property="og:description"
            content="Rent services, products and homes with NFT technology"
          />
          <meta
            property="og:image"
            content="https://market.luvnft.com/wp-content/uploads/2022/04/NFT-RENTAL-MARKETPLACE.jpg"
          />

          <meta property="twitter:card" content="summary_large_image" />
          <meta property="twitter:url" content="https://rent.luvnft.com/" />
          <meta property="twitter:title" content="RENT LUV NFT MARKETPLACE" />
          <meta
            property="twitter:description"
            content="Rent services, products and homes with NFT technology"
          />
          <meta
            property="twitter:image"
            content="https://market.luvnft.com/wp-content/uploads/2022/04/NFT-RENTAL-MARKETPLACE.jpg"
          />
        </Head>
      </div>
      <Component {...pageProps} />
    </div>
  );
}

export default MyApp;
